export const AppRouter = {
  login: "login",
  signup: "signup",
  home: "Trang chủ",
  books: "books",
  bookDetail: "Chi tiết",
  bookView: "book_view",
  search: "Tìm kiếm",
  category: "Thể loại",
  categoryDetail: "Thể loại chi tiết",
  library: "Thư viện",
  setting: "Cài đặt",
  splash: "Start",
  member: "member",
  payment: "payment",
  updateProfile: "Cập nhật tài khoản",
  changePassword: "Đổi mật khẩu",
};
