export const AppRouter = {
  login: 'login',
  signup: 'signup',
  home: 'Trang chủ',
  books: 'books',
  bookDetail: 'Chi tiết',
  bookView: 'book_view',
  bookAdvertising: 'book_advertising',
  search: 'Tìm kiếm',
  category: 'Thể loại',
  categoryDetail: 'Thể loại chi tiết',
  library: 'Thư viện',
  setting: 'Cài đặt',
  splash: 'Start',
  member: 'member',
  payment: 'payment',
  account: 'Tài khoản',
  updateProfile: 'Cập nhật tài khoản',
  changePassword: 'Đổi mật khẩu',
  rewards: 'Đổi thưởng',
}
